import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { Orbitron } from 'next/font/google';

import './globals.css';

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--roboto',
  weight: ['300', '400', '500', '700'],
});

const orbitron = Orbitron({
  subsets: ['latin'],
  variable: '--orbitron',
  weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${roboto.variable} ${orbitron.variable}`}>
        {children}
      </body>
    </html>
  );
}
