import type { Metadata } from 'next';
import { roboto, orbitron } from '@/app/ui/fonts';
import '@/app/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${roboto.variable} ${orbitron.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
